rust:
  repo: https://github.com/breez/spark-sdk
  rev: 7009d6c722a11464642e0d5b7187e58257fac4df
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkSpark
turboModule:
  cpp: cpp
  ts: src