rust:
  repo: https://github.com/breez/spark-sdk
  rev: 2263b5f2ab3e56ba952f8d68930e6f0badacfc33
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkSpark
turboModule:
  cpp: cpp
  ts: src