rust:
  repo: https://github.com/breez/spark-sdk
  rev: 4c48a2e5a46617ccf3fd5516cdd93aadc28d72af
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkSpark
turboModule:
  cpp: cpp
  ts: src