rust:
  repo: https://github.com/breez/spark-sdk
  rev: 61c1c40b2eeca0d1ad431a4d3ea7b64100dd7998
  manifestPath: crates/breez-sdk/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkSpark
turboModule:
  cpp: cpp
  ts: src